### ISSUE TITLE
seeding.csv

### ISSUE THREAD

**Issue by khwilson** [HopkinsIDD/COVIDScenarioPipeline#84]
Hi there. I'm trying to get this setup working in Rhode Island and I am 100% stuck at seeding.csv. I can't seem to actually find a file that creates it, and the examples that are referenced are not present in the repository.

Could you advise?

Many thanks!

**Comment by jkamins7** [comment]
seeding.csv is a three column csv with columns : place,date,amount
 - place is a geoid (one of the ones in geodata.csv)
 - date is the date of infection
 - amount is the percentage of the population that gets infected on that day

https://github.com/HopkinsIDD/COVID19_Minimal is a minimal working example of how to use this pipeline, and has an example [seeding csv](https://github.com/HopkinsIDD/COVID19_Minimal/blob/master/data/minimal/seeding.csv)

**Comment by jcblemai** [comment]
In order to start your model, in the config.yaml file
```
seeding:
  method: PoissonDistributed
  lambda_file: data/rhodes-island/seeding.csv
```
The `seeding.csv` files needs to have at least three columns named `place,date,amount` . Place is a place that match exactly a place in the `geodata.csv`. Date is a date in any sensible format, and amount the lambda parameter of the Poisson distribution.

To start quickly, you can create it in excel (or anything somewhat like this): 
1. open `geodata.csv`, and do "save as" `seeding.csv`
2. change the column name with the geoid or anything to name it `place`
3. Add a column `date` and put the date where you want the model seeded. This can be the start date of your model or any date after the model is 
4. Add a column named "amount". Put the amount. What you can usually do is put 0.1 in places where no cases has been found (so there is still a chance that some simulations starts something there), and the cum cases of the last like 4-5 days multiplied by 5 for a county with cases.

For each simulation, the model will draw from a Poisson distribution centered on `amount`

**Comment by khwilson** [comment]
Perfect! Thank you. :-)
